"""initial delivery and tracking schema

Revision ID: dd5526d7994f
Revises:
Create Date: 2026-06-02 17:56:25.502205

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd5526d7994f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deliveries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hub_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("assigned_driver_id", sa.UUID(), nullable=True),
        sa.Column("pickup_address", sa.String(), nullable=False),
        sa.Column("delivery_address", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("zip_code", sa.String(), nullable=False),
        sa.Column("parcel_count", sa.Integer(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("service_type", sa.String(), nullable=False),
        sa.Column("priority", sa.String(), server_default="Normal", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "assigned",
                "picked_up",
                "in_transit",
                "delivered",
                "cancelled",
                name="deliverystatus",
            ),
            server_default="created",
            nullable=False,
        ),
        sa.Column("expected_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deliveries_assigned_driver_id"),
        "deliveries",
        ["assigned_driver_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deliveries_customer_id"), "deliveries", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_deliveries_hub_id"), "deliveries", ["hub_id"], unique=False
    )
    op.create_table(
        "tracking_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tracking_events_delivery_id"),
        "tracking_events",
        ["delivery_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracking_events_delivery_id"), table_name="tracking_events")
    op.drop_table("tracking_events")
    op.drop_index(op.f("ix_deliveries_hub_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_customer_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_assigned_driver_id"), table_name="deliveries")
    op.drop_table("deliveries")
    # ### end Alembic commands ###
