"""delivery references + counter

Revision ID: e4f651c21d3f
Revises: 8b483039f02a
Create Date: 2026-06-09 22:01:09.959264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4f651c21d3f"
down_revision: Union[str, Sequence[str], None] = "8b483039f02a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "counters",
        sa.Column("entity", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("entity", "year"),
    )
    op.add_column("deliveries", sa.Column("reference", sa.String(), nullable=False))
    op.create_index(
        op.f("ix_deliveries_reference"), "deliveries", ["reference"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deliveries_reference"), table_name="deliveries")
    op.drop_column("deliveries", "reference")
    op.drop_table("counters")
    # ### end Alembic commands ###
