"""driver reference + counters

Revision ID: a48414fc38f2
Revises: aa7734aba92d
Create Date: 2026-06-09 22:04:57.462663

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a48414fc38f2"
down_revision: Union[str, Sequence[str], None] = "aa7734aba92d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "counters",
        sa.Column("entity", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("entity", "year"),
    )
    op.add_column("drivers", sa.Column("reference", sa.String(), nullable=False))
    op.create_index(op.f("ix_drivers_reference"), "drivers", ["reference"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_drivers_reference"), table_name="drivers")
    op.drop_column("drivers", "reference")
    op.drop_table("counters")
    # ### end Alembic commands ###
