"""driver hub_id

Revision ID: bfe5c5f393f6
Revises: 9d93ab25c9fd
Create Date: 2026-06-09 20:15:42.302455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bfe5c5f393f6"
down_revision: Union[str, Sequence[str], None] = "9d93ab25c9fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("drivers", sa.Column("hub_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_drivers_hub_id"), "drivers", ["hub_id"], unique=False)
    op.create_foreign_key(
        None, "drivers", "hubs", ["hub_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "drivers", type_="foreignkey")
    op.drop_index(op.f("ix_drivers_hub_id"), table_name="drivers")
    op.drop_column("drivers", "hub_id")
    # ### end Alembic commands ###
