"""customer city zip reference

Revision ID: c95643c9c86a
Revises: a48414fc38f2
Create Date: 2026-06-10 07:00:27.627787

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c95643c9c86a"
down_revision: Union[str, Sequence[str], None] = "a48414fc38f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customers", sa.Column("city", sa.String(), nullable=False))
    op.add_column("customers", sa.Column("zip_code", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "zip_code")
    op.drop_column("customers", "city")
    # ### end Alembic commands ###
