"""customer reference

Revision ID: e6df70bf3044
Revises: c95643c9c86a
Create Date: 2026-06-10 07:22:22.619685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6df70bf3044"
down_revision: Union[str, Sequence[str], None] = "c95643c9c86a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customers", sa.Column("reference", sa.String(), nullable=False))
    op.create_index(
        op.f("ix_customers_reference"), "customers", ["reference"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_customers_reference"), table_name="customers")
    op.drop_column("customers", "reference")
    # ### end Alembic commands ###
