"""hub city zip

Revision ID: fa2d3511d7ad
Revises: bfe5c5f393f6
Create Date: 2026-06-09 21:15:51.158088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2d3511d7ad'
down_revision: Union[str, Sequence[str], None] = 'bfe5c5f393f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hubs', sa.Column('city', sa.String(), nullable=True))
    op.add_column('hubs', sa.Column('zip_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hubs', 'zip_code')
    op.drop_column('hubs', 'city')
    # ### end Alembic commands ###
