"""initial reporting migration

Revision ID: 1021e4eff82a
Revises:
Create Date: 2026-06-09 12:21:51.020977

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1021e4eff82a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_facts",
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(), server_default="created", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expected_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("on_time", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("delivery_id"),
    )
    op.create_index(
        op.f("ix_delivery_facts_created_at"),
        "delivery_facts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_delivery_facts_customer_id"),
        "delivery_facts",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        "ix_delivery_facts_status_completed",
        "delivery_facts",
        ["status", "completed_at"],
        unique=False,
    )
    op.create_table(
        "driver_states",
        sa.Column("driver_id", sa.UUID(), nullable=False),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("driver_id"),
    )
    op.create_table(
        "incident_facts",
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("delivery_id", sa.UUID(), nullable=True),
        sa.Column("declared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_month", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("incident_id"),
    )
    op.create_index(
        op.f("ix_incident_facts_delivery_id"),
        "incident_facts",
        ["delivery_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_facts_period_month"),
        "incident_facts",
        ["period_month"],
        unique=False,
    )
    op.create_table(
        "kpi_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("period_month", sa.Date(), nullable=False),
        sa.Column("total_deliveries", sa.Integer(), server_default="0", nullable=False),
        sa.Column("on_time_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "avg_delivery_time_h", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column(
            "customer_satisfaction", sa.Numeric(precision=3, scale=2), nullable=True
        ),
        sa.Column(
            "revenue",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("active_drivers", sa.Integer(), server_default="0", nullable=False),
        sa.Column("incidents_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "source",
            sa.Enum("seeded", "computed", name="kpisource"),
            server_default="computed",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kpi_snapshots_period_month"),
        "kpi_snapshots",
        ["period_month"],
        unique=True,
    )
    op.create_table(
        "revenue_facts",
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column(
            "amount",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("period_month", sa.Date(), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("invoice_id"),
    )
    op.create_index(
        op.f("ix_revenue_facts_customer_id"),
        "revenue_facts",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_revenue_facts_period_month"),
        "revenue_facts",
        ["period_month"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_revenue_facts_period_month"), table_name="revenue_facts")
    op.drop_index(op.f("ix_revenue_facts_customer_id"), table_name="revenue_facts")
    op.drop_table("revenue_facts")
    op.drop_index(op.f("ix_kpi_snapshots_period_month"), table_name="kpi_snapshots")
    op.drop_table("kpi_snapshots")
    op.drop_index(op.f("ix_incident_facts_period_month"), table_name="incident_facts")
    op.drop_index(op.f("ix_incident_facts_delivery_id"), table_name="incident_facts")
    op.drop_table("incident_facts")
    op.drop_table("driver_states")
    op.drop_index("ix_delivery_facts_status_completed", table_name="delivery_facts")
    op.drop_index(op.f("ix_delivery_facts_customer_id"), table_name="delivery_facts")
    op.drop_index(op.f("ix_delivery_facts_created_at"), table_name="delivery_facts")
    op.drop_table("delivery_facts")
    # ### end Alembic commands ###
